kibot:
  version: 1
  
preflight:
  # [boolean=false] Zones are filled before doing any operation involving PCB layers.
  check_zone_fills: true
  # [list(dict)] A list of entries to filter out ERC/DRC messages.
  # filters: 
  #   - filter: 'Filter description'
  #     error: '10'
  #     regex: 'Regular expression to match'
  # [boolean=false] Option for `run_drc`. Ignores the unconnected nets. Useful if you didn't finish the routing.
  ignore_unconnected: false
  # [boolean=false] Runs the DRC (Distance Rules Check). To ensure we have a valid PCB.
  # The report file name is controlled by the global output pattern (%i=drc %x=txt).
  run_drc: false
  # [boolean=false] Runs the ERC (Electrical Rules Check). To ensure the schematic is electrically correct.
  # The report file name is controlled by the global output pattern (%i=erc %x=txt).
  run_erc: true
  # [boolean=false] Update the XML version of the BoM (Bill of Materials).
  # To ensure our generated BoM is up to date.
  # Note that this isn't needed when using the internal BoM generator (`bom`).
  update_xml: true

outputs:
  - name: 'print schema'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: 'docs/pdf'
    options:
      output: '%p-Schematic.%x'

  - name: 'print board'
    comment: "Print board (PDF) front"
    type: pdf_pcb_print
    layers:
      - layer: Edge.Cuts
      - layer: F.CrtYd
      - layer: F.Fab
    dir: 'docs/pdf'
    options:
      output: '%p-Board_top.%x'

  - name: 'print board'
    comment: "Print board (PDF) bottom"
    type: pdf_pcb_print
    layers:
      - layer: Edge.Cuts
      - layer: B.CrtYd
      - layer: B.Fab
    dir: 'docs/pdf'
    options:
      output: '%p-Board_bottom.%x'

  - name: 'print schema'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: 'docs/img'
    options:
      output: '%p-Schematic.%x'

  # PcbDraw - Beautiful 2D PCB render:
  # Uses configurable colors.
  # Can also render the components if the 2D models are available
  - name: 'plot images of pcb TOP'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'docs/img'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: false
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)] list of components to highlight
      # highlight:
      # [list(string)] list of libraries
      libs: ['/usr/share/pcbdraw/footprints/KiCAD-base']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i.%x'] name for the generated file . Affected by global options
      output: '%f-Board_%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [string|list(string)] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/usr/share/pcbdraw/styles/jlcpcb-green-hasl.json'
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'visible'

  - name: 'plot images of pcb BOTTOM'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'docs/img'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: true
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)] list of components to highlight
      # highlight:
      # [list(string)] list of libraries
      # libs: ['/usr/share/pcbdraw/footprints/KiCAD-base']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i.%x'] name for the generated file . Affected by global options
      output: '%f-Board_%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [string|list(string)] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/usr/share/pcbdraw/styles/jlcpcb-green-hasl.json'
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'visible'

  - name: Step
    comment: "Generate 3D model (STEP)"
    type: step
    dir: docs/CAD
    options:
      metric_units: true
      origin: grid         # "grid" or "drill" o "X,Y" i.e. 3.2,-10
      no_virtual: true     # exclude 3D models for components with 'virtual' attribute
      output: '%f.%x'
