name: "Kibot builder"

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: config.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: Combine PDFs
      shell: bash
      run: |
        bash scripts/combine_pdf.sh docs/docs/pdf
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  test:
    name: test_output
    needs: [export]
    runs-on: ubuntu-latest #self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Extract artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Push assets
        shell: bash
        run: |
          bash scripts/push_assets.sh

  release:
    name: release version
    if: startsWith(github.ref, 'refs/tags/')
    needs: [export]
    runs-on: ubuntu-latest #self-hosted
    steps:
      - name: Extract artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs/img/nanosaur-exp-board-Board_bottom.svg
          asset_name: docs/img/nanosaur-exp-board-Board_bottom.svg
          asset_content_type: application/svg
