name: "Kibot builder"

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: config.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    # https://github.com/amoeba/combine-pdf-action
    - name: Combine PDFs
      id: combine
      uses: amoeba/combine-pdf-action@v1
      with:
        path: docs/docs/pdf
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  test:
    name: test push to website
    needs: [export]
    runs-on: ubuntu-latest #self-hosted
    steps:
      # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
      - name: Extract artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/img'
          destination_repo: 'rnanosaur/rnanosaur.github.io'
          destination_folder: 'assets/docs/expansion-board'
          user_email: 'raffaello@rnext.it'
          user_name: 'rbonghi'
          commit_message: 'Push updated expansion board images'

  release:
    name: release version
    if: startsWith(github.ref, 'refs/tags/')
    needs: [export]
    runs-on: ubuntu-latest #self-hosted
    steps:
      - uses: actions/checkout@v2
      # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
      - name: Extract artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Push assets
        shell: bash
        run: |
          bash scripts/push_assets.sh docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

