name: "Kibot builder"

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push, pull_request]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: config.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: Combine PDFs
      id: combine
      uses: amoeba/combine-pdf-action@v1
      with:
        path: docs/docs/pdf
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  release:
    name: release version
    if: startsWith(github.ref, 'refs/tags/')
    needs: [export]
    runs-on: ubuntu-latest #self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Extract artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Push assets
        shell: bash
        run: |
          bash scripts/push_assets.sh docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

